### ISSUE TITLE
Rspecについて調べる

### ISSUE THREAD

**Issue by ms2sato** [cino3/HiramekiMart#1]
作成したモデルをテストしたりするために、ユニットテストのライブラリの一つであるRspecのことを調べましょう（もしも「そもそもユニットテストとは何か」が疑問になっていたら、それも調べてみてください。調べた内容やURLをこのIssueにまとめてみてください）。

**Comment by cino3** [comment]
# Rspecのことを調べました

> **Railsのテストについて**（特にユニットテスト）

Railsのテストは主に下記の３つに分類される。
**ユニットテスト**はその中のひとつでモデルに対しておこなうテスト。

①ユニットテスト
　モデル対処にテストを行う
　・モデルの検索系メソッドが正しい値を取得できるか
　・モデルの更新系メソッドが正しくデータベースを更新できるか
　・モデルの更新系メソッドが不正な入力に対して、適切なエラーを発生させるか

②ファンクションテスト
　モデルからビュー、コントローラまで含む、アクションごとのテストを行う
　
③インテグレーションテスト
　アクション間をまたぐテストなどを行う

>**RSpecとは**

Rubyのテストフレームワークの一つで、Railsプログラマの間で高い人気を獲得している。
ユニットテスト以外のこともできる。
用語法や書き方が独特である。
RSpecは、BDD（ビヘイビア駆動開発/ふるまい駆動開発）を実践するためのツール。

> **TDD/BDDの開発サイクル**

下記の1～3を繰り返す。
1. 失敗するテストを書く
2. 最小限のコードをかいてテストをパスさせる
3. リファクタリング

参考にしたサイト
http://railsdoc.com/test
https://thinkit.co.jp/story/2014/07/08/5092
https://www.oiax.jp/rails/rspec_capybara_primer.html

**Comment by ms2sato** [comment]
@cino3 よくまとまっていますね！無駄ない形で良いと思います。ひょっとすると実感としてはまだ掴みきれていない可能性もあるので、今度対面の時に確認させてくださいね。実際にRspecで簡単なテストを書いてみる #2 をやってみましょう。

**Comment by cino3** [comment]
@ms2sato ご確認ありがとうございました。
はい、まだ実感はできていないので対面時はよろしくお願いいたします。

**Comment by ms2sato** [comment]
確認までしたのでclose
