### ISSUE TITLE
ログインチェックをする

### ISSUE THREAD

**Issue by ms2sato** [cino3/HiramekiMart#11]
今、ログインしていない場合のチェックがなされていないと思います。
どこに、どんな処理を入れたら良いか提案してくださいー。

**Comment by cino3** [comment]
> ログインチェックについて考えてみました。よろしくお願いいたします。

○下記のアクションについてはログインチェックを行わない
　　itemコントローラのindexアクション
　　itemコントローラのshowアクション

○それ以外のアクションが呼び出されたら、deviseの『authenticate_user!』メソッドを使って、ログイン画面にリダイレクトさせる。

○ログイン画面にリダイレクトした時に、diveiceのフラッシュメッセージを表示させる。

**Comment by ms2sato** [comment]
@cino3 概ね良さそうですね。実装してみましょう！

http://qiita.com/ppworks/items/f68f68a343fc88a76ad4

などを参考にすると良いかな？

**Comment by cino3** [comment]
ログインチェック機能を作成しました。お手すきの時によろしくお願いいたします。
