### ISSUE TITLE
「お気に入り」機能の設計

### ISSUE THREAD

**Issue by ms2sato** [cino3/HiramekiMart#13]
ER図にお気に入りを実現するためのテーブルを書き足してください。
書いたらURLをこのIssueに貼り付けていただけたらレビューします。

以下大まかな仕様です。もし不足あったら適宜質問してください。

- ユーザーがItemに対してお気に入りを複数保持することができる
- Itemには現在のお気に入り数が表示できるようになる想定
- ユーザーのマイページにはお気に入り一覧が表示できるようになる想定

**Comment by cino3** [comment]
favoriteテーブルを追加いたしました。
https://cacoo.com/diagrams/dHmHAsSdYwIRR0yG

**Comment by ms2sato** [comment]
@cino3 OKです！実装しましょう！まず自分でIssueを立てましょうか。立てたIssueの中に、この機能を実現するのに必要なことを大まかに書いてみてください（例: favoritesテーブルをマイグレーションする）

**Comment by cino3** [comment]
**お気に入り機能に、必要そうな作業を挙げてみました。お手すきの時にご確認よろしくお願いいたします。**

> モデル

- favoritesテーブルをマイグレーションする
- userモデル、itemモデル、favoriteモデルでテーブルのリレーションを設定する
userモデルでは　has_many : favorite_items, through: :favirites, source: :items
として、ログインユーザのお気に入りのItemを取得できるようにする

> コントローラ

- favoritesコントローラを作成する
- お気に入りを実行する　addfavアクションを作成　（post）
- お気に入りを取り消す　removefavアクション作成  （post）

> ルーティング

- add_favアクションへのルーティングを設定
- remove_favアクションへのルーティングを設定

> view

- アイテム詳細画面にお気に入りボタンを作成する
- アイテム詳細画面にお気に入り取り消しボタンを作成する
- アイテム詳細画面のお気に入りボタンとお気に入り取り消しボタンが状況に応じて一方だけが表示されるようにする
- アイテム一覧の画面で各アイテムのお気に入りされている数が表示されるようにする
- プロフィール画面でのお気に入り一覧を表示させる
- アイテム一覧の画面をパーシャルにして、アイテム一覧の画面とプロフィール画面で使用できるようにする

**Comment by ms2sato** [comment]
@cino3 網羅的で素晴らしいです！書いてくれた部分に関しては「何をすれば良いか」が見えていることが伺えます。

## モデルについて

> このアクションの中身をモデルに書くのが良いと思うのですが、
> どう実現させるのかわかりませんでした。

この感覚とても良いですね。

https://github.com/cino3/HiramekiMart/issues/14
このIssueを作成してみました。読んでもらうとモデルの実装について理解ができるかも。
先に #14 をやってみましょう！

## コントローラやルーティング

今回は下記のようなUserにぶら下がったFavoriteを扱うと思います。こういう親子関係をプログラミングの一般的な言葉で「ネスト」と呼びます。

`/user/:user_id/favorites`

その場合のルーティングですが、下記が参考になるかもしれません。
https://techracho.bpsinc.jp/baba/2014_03_03/15619

また、URLやアクションの考え方ですが、なるべくRESTの思想に近づけるのが良いです。

> - お気に入りを実行する　addfavアクションを作成　（post）
> - お気に入りを取り消す　removefavアクション作成 （post）

この部分は
- `favorites` への POSTで新規作成
- `favorites/:id` へのDELETEで削除
※これはscaffoldで作成されるものとよく似ていますよね。

とします。


あえて今は答えは書かないので一度考えてみてください。ただ、1時間考えてみてわからなければ再度相談いただければ幸いです。その時は考えたことなど是非教えてください。


## まとめ
この後やってみて欲しいことは以下二点です。

- #14 を実装する
- ルーティングやコントローラのネストについて考えて、このIssueに再度考えを投稿する

**Comment by cino3** [comment]
コントローラやルーティングについて考えてみました。

## コントローラ
userコントローラに次のアクションを追加

- user#addfav  　(お気に入りを追加する)
- user#delfav　　(お気に入りを削除する)

## ルーティング
ネストしたルーティングを使って下記のルーティングを追加する

- /users/:user_id/addfav　　　　　　　　　=> user#addfav
- /users/:user_id/items/:item_id/delfav      => user#delfav
- 

設定例
```
    resources :users do
      post 'addfav'
      resources :items do        
        delete 'delfav'
      end
    end
```

**Comment by ms2sato** [comment]
@cino3 素晴らしい！`shallow`を入れているのも気が利いています。`POST`や`DELETE`の感覚も身についていると嬉しいです（ここは対面で確認させてください）。 #17 を作りました！

**Comment by ms2sato** [comment]
設計はできたのでclose
