### ISSUE TITLE
「お気に入り」機能の実装

### ISSUE THREAD

**Issue by ms2sato** [cino3/HiramekiMart#17]
#13 に沿って実装する。

#14 がまだマージされていないので、モデルにまつわる部分は後回しで進めると良いでしょう。 #14 がマージされたら、こちらの作業のブランチに masterをマージすればうまくいくはずです（gitの練習にもなるのでチャレンジすると良いでしょう）。

**Comment by ms2sato** [comment]
@cino3 現在のメインタスクはこれなので、最初はこれを進めていただければ大丈夫です！

長くなりそうなので例えば下記くらいで一旦区切っていくのも良いですね。その場合、その他のタスクは自分でIssueにしてみてください。

- アイテム詳細画面にお気に入りボタンを作成する
- アイテム詳細画面にお気に入り取り消しボタンを作成する
- アイテム詳細画面のお気に入りボタンとお気に入り取り消しボタンが状況に応じて一方だけが表示されるようにする

**Comment by cino3** [comment]
現在のメインタスクについて承知いたしました！
やはり長くなりそうなのでissueを一つ作成しました。

**Comment by ms2sato** [comment]
@cino3 承知です！ レビュー依頼する時には私にアサインくれれば見ていきますねー。
