### ISSUE TITLE
Itemの権限について実装する

### ISSUE THREAD

**Issue by ms2sato** [cino3/HiramekiMart#4]
Itemは「作った人だけが更新や削除操作ができて、それ以外の人は見ることしかできない」
という性質を持っています（他人に編集されたら困ってしまいますよね）。

なので、権限の管理を実装しましょう。

- `Item#editable_by?(user)` メソッドを実装する。このメソッドは、引数`user`で与えられたユーザが、このItemを操作していいか調べるためのメソッドです。
- もしも、Itemを作成したユーザと`user`が同一ならtrue、さもなくばfalseを返します。

テストは #2 がマージされたら書くので、別のIssueでやります（このIssueではテストを書かなくて大丈夫です。チェックは `bin/rails c` で行えると思いますが、やったことありますか？）。

**Comment by cino3** [comment]
bin/rails c　は知っているコマンドは少ないですが、やったことはあるのでやってみるです。

**Comment by ms2sato** [comment]
@cino3 はい！試してみて、ちょっとよくわからなかったりしたら気軽に質問くださいねー。
